# Generated by Django 4.2.6 on 2023-12-03 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_image_category_id_delete_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='negative_prompt',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='image',
            name='prompt',
            field=models.CharField(default='', max_length=255),
        ),
    ]
